name: Publish

on:
  push:
    tags:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.3.0

      - name: Publishing
        run: |
          npm install
          npm run build
          npm publish

        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
